# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 1000)
        MainWindow.setStyleSheet("background-color: rgb(245, 245, 175)")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 861, 321))
        self.tableWidget.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Print_print = QtWidgets.QPushButton(self.centralwidget)
        self.Print_print.setGeometry(QtCore.QRect(230, 550, 50, 30))
        self.Print_print.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_print.setObjectName("Print_print")
        self.Print_customer = QtWidgets.QPushButton(self.centralwidget)
        self.Print_customer.setGeometry(QtCore.QRect(230, 600, 50, 30))
        self.Print_customer.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_customer.setObjectName("Print_customer")
        self.Print_order = QtWidgets.QPushButton(self.centralwidget)
        self.Print_order.setGeometry(QtCore.QRect(230, 750, 50, 30))
        self.Print_order.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_order.setObjectName("Print_order")
        self.Print_dist = QtWidgets.QPushButton(self.centralwidget)
        self.Print_dist.setGeometry(QtCore.QRect(230, 800, 50, 30))
        self.Print_dist.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_dist.setObjectName("Print_dist")
        self.Print_prop = QtWidgets.QPushButton(self.centralwidget)
        self.Print_prop.setGeometry(QtCore.QRect(230, 850, 50, 30))
        self.Print_prop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_prop.setObjectName("Print_prop")
        self.Print_product = QtWidgets.QPushButton(self.centralwidget)
        self.Print_product.setGeometry(QtCore.QRect(230, 650, 50, 30))
        self.Print_product.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_product.setObjectName("Print_product")
        self.Q_3_8_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_8.setGeometry(QtCore.QRect(430, 580, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Q_3_8_8.setFont(font)
        self.Q_3_8_8.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_8.setObjectName("Q_3_8_8")
        self.Q_3_8_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_9.setGeometry(QtCore.QRect(430, 620, 401, 31))
        self.Q_3_8_9.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_9.setObjectName("Q_3_8_9")
        self.Q_3_8_10 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_10.setGeometry(QtCore.QRect(430, 660, 401, 31))
        self.Q_3_8_10.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_10.setObjectName("Q_3_8_10")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 480, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.Q_3_8_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_7.setGeometry(QtCore.QRect(670, 520, 41, 31))
        self.Q_3_8_7.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_7.setObjectName("Q_3_8_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 330, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 32px;\n"
"font: \"Arial Black\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Q_3_8_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_1.setGeometry(QtCore.QRect(450, 440, 41, 31))
        self.Q_3_8_1.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_1.setObjectName("Q_3_8_1")
        self.Q_3_8_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_4.setGeometry(QtCore.QRect(780, 440, 41, 31))
        self.Q_3_8_4.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_4.setObjectName("Q_3_8_4")
        self.Q_3_8_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_6.setGeometry(QtCore.QRect(560, 520, 41, 31))
        self.Q_3_8_6.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_6.setObjectName("Q_3_8_6")
        self.Q_3_8_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_5.setGeometry(QtCore.QRect(450, 520, 41, 31))
        self.Q_3_8_5.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_5.setObjectName("Q_3_8_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 389, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Q_3_8_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_3.setGeometry(QtCore.QRect(670, 440, 41, 31))
        self.Q_3_8_3.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_3.setObjectName("Q_3_8_3")
        self.Q_3_8_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_2.setGeometry(QtCore.QRect(560, 440, 41, 31))
        self.Q_3_8_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_2.setObjectName("Q_3_8_2")
        self.Q_3_9_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_1.setGeometry(QtCore.QRect(430, 700, 401, 31))
        self.Q_3_9_1.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_1.setObjectName("Q_3_9_1")
        self.Q_3_9_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_3.setGeometry(QtCore.QRect(430, 780, 401, 31))
        self.Q_3_9_3.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_3.setObjectName("Q_3_9_3")
        self.Q_3_9_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_2.setGeometry(QtCore.QRect(430, 740, 401, 31))
        self.Q_3_9_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_2.setObjectName("Q_3_9_2")
        self.Q_3_9_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_4.setGeometry(QtCore.QRect(430, 820, 401, 31))
        self.Q_3_9_4.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_4.setObjectName("Q_3_9_4")
        self.Q_3_9_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_6.setGeometry(QtCore.QRect(430, 900, 401, 31))
        self.Q_3_9_6.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_6.setObjectName("Q_3_9_6")
        self.Q_3_9_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_5.setGeometry(QtCore.QRect(430, 860, 401, 31))
        self.Q_3_9_5.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_5.setObjectName("Q_3_9_5")
        self.add_customer = QtWidgets.QPushButton(self.centralwidget)
        self.add_customer.setGeometry(QtCore.QRect(330, 600, 50, 30))
        self.add_customer.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_customer.setObjectName("add_customer")
        self.add_product = QtWidgets.QPushButton(self.centralwidget)
        self.add_product.setGeometry(QtCore.QRect(330, 650, 50, 30))
        self.add_product.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_product.setObjectName("add_product")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 330, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 550, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 600, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 650, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 750, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 800, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 850, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.add_print = QtWidgets.QPushButton(self.centralwidget)
        self.add_print.setGeometry(QtCore.QRect(330, 550, 50, 30))
        self.add_print.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_print.setObjectName("add_print")
        self.add_order = QtWidgets.QPushButton(self.centralwidget)
        self.add_order.setGeometry(QtCore.QRect(330, 750, 50, 30))
        self.add_order.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_order.setObjectName("add_order")
        self.add_dist = QtWidgets.QPushButton(self.centralwidget)
        self.add_dist.setGeometry(QtCore.QRect(330, 800, 50, 30))
        self.add_dist.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_dist.setObjectName("add_dist")
        self.add_prop = QtWidgets.QPushButton(self.centralwidget)
        self.add_prop.setGeometry(QtCore.QRect(330, 850, 50, 30))
        self.add_prop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_prop.setObjectName("add_prop")
        self.print = QtWidgets.QPushButton(self.centralwidget)
        self.print.setGeometry(QtCore.QRect(30, 410, 41, 31))
        self.print.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.print.setObjectName("print")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(30, 470, 41, 31))
        self.add.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add.setObjectName("add")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(90, 410, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(90, 470, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(240, 410, 161, 31))
        self.DeleteButton.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.DeleteButton.setObjectName("DeleteButton")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 900, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.add_prod_type = QtWidgets.QPushButton(self.centralwidget)
        self.add_prod_type.setGeometry(QtCore.QRect(330, 900, 50, 30))
        self.add_prod_type.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_prod_type.setObjectName("add_prod_type")
        self.Print_prod_type = QtWidgets.QPushButton(self.centralwidget)
        self.Print_prod_type.setGeometry(QtCore.QRect(230, 900, 50, 30))
        self.Print_prod_type.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_prod_type.setObjectName("Print_prod_type")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 700, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.add_format = QtWidgets.QPushButton(self.centralwidget)
        self.add_format.setGeometry(QtCore.QRect(330, 700, 50, 30))
        self.add_format.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_format.setObjectName("add_format")
        self.Print_format = QtWidgets.QPushButton(self.centralwidget)
        self.Print_format.setGeometry(QtCore.QRect(230, 700, 50, 30))
        self.Print_format.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_format.setObjectName("Print_format")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Бойко С.Р., ПИ-20а, курсовая работа БД, вариант №13"))
        self.Print_print.setText(_translate("MainWindow", "П"))
        self.Print_customer.setText(_translate("MainWindow", "П"))
        self.Print_order.setText(_translate("MainWindow", "П"))
        self.Print_dist.setText(_translate("MainWindow", "П"))
        self.Print_prop.setText(_translate("MainWindow", "П"))
        self.Print_product.setText(_translate("MainWindow", "П"))
        self.Q_3_8_8.setText(_translate("MainWindow", "левое внешнее соединение"))
        self.Q_3_8_9.setText(_translate("MainWindow", "правое внешнее соединение"))
        self.Q_3_8_10.setText(_translate("MainWindow", "запрос на запросе по принципу левого соединения "))
        self.label_5.setText(_translate("MainWindow", "симметричное внутреннее соединение без условия "))
        self.Q_3_8_7.setText(_translate("MainWindow", "3"))
        self.label_6.setText(_translate("MainWindow", "Выполнить запрос"))
        self.Q_3_8_1.setText(_translate("MainWindow", "1"))
        self.Q_3_8_4.setText(_translate("MainWindow", "4"))
        self.Q_3_8_6.setText(_translate("MainWindow", "2"))
        self.Q_3_8_5.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "симметричное внутреннее соединение с условием"))
        self.Q_3_8_3.setText(_translate("MainWindow", "3"))
        self.Q_3_8_2.setText(_translate("MainWindow", "2"))
        self.Q_3_9_1.setText(_translate("MainWindow", "итоговый запрос без условия "))
        self.Q_3_9_3.setText(_translate("MainWindow", "итоговый запрос с условием на группы"))
        self.Q_3_9_2.setText(_translate("MainWindow", "итоговый запрос с условием на данные"))
        self.Q_3_9_4.setText(_translate("MainWindow", "итоговый запрос с условием на данные и на группы "))
        self.Q_3_9_6.setText(_translate("MainWindow", "запрос с подзапросом "))
        self.Q_3_9_5.setText(_translate("MainWindow", "запрос на запросе по принципу итогового запроса "))
        self.add_customer.setText(_translate("MainWindow", "Д"))
        self.add_product.setText(_translate("MainWindow", "Д"))
        self.label_2.setText(_translate("MainWindow", "Вы работаете в режиме администратора!"))
        self.label_3.setText(_translate("MainWindow", "Типографии"))
        self.label_4.setText(_translate("MainWindow", "Заказчики"))
        self.label_8.setText(_translate("MainWindow", "Изделия"))
        self.label_9.setText(_translate("MainWindow", "Заказы"))
        self.label_10.setText(_translate("MainWindow", "Районы"))
        self.label_12.setText(_translate("MainWindow", "Тип собственности"))
        self.add_print.setText(_translate("MainWindow", "Д"))
        self.add_order.setText(_translate("MainWindow", "Д"))
        self.add_dist.setText(_translate("MainWindow", "Д"))
        self.add_prop.setText(_translate("MainWindow", "Д"))
        self.print.setText(_translate("MainWindow", "П"))
        self.add.setText(_translate("MainWindow", "Д"))
        self.label_14.setText(_translate("MainWindow", "- просмотреть"))
        self.label_15.setText(_translate("MainWindow", "- добавить"))
        self.DeleteButton.setText(_translate("MainWindow", "Удалить запись"))
        self.label_16.setText(_translate("MainWindow", "Вид изделия"))
        self.add_prod_type.setText(_translate("MainWindow", "Д"))
        self.Print_prod_type.setText(_translate("MainWindow", "П"))
        self.label_11.setText(_translate("MainWindow", "Формат листов"))
        self.add_format.setText(_translate("MainWindow", "Д"))
        self.Print_format.setText(_translate("MainWindow", "П"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
