# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 1000)
        MainWindow.setStyleSheet("background-color: rgb(245, 245, 175)")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1051, 321))
        self.tableWidget.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Print_print = QtWidgets.QPushButton(self.centralwidget)
        self.Print_print.setGeometry(QtCore.QRect(230, 530, 80, 30))
        self.Print_print.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_print.setObjectName("Print_print")
        self.Print_customer = QtWidgets.QPushButton(self.centralwidget)
        self.Print_customer.setGeometry(QtCore.QRect(230, 580, 80, 30))
        self.Print_customer.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_customer.setObjectName("Print_customer")
        self.Print_order = QtWidgets.QPushButton(self.centralwidget)
        self.Print_order.setGeometry(QtCore.QRect(230, 780, 80, 30))
        self.Print_order.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_order.setObjectName("Print_order")
        self.Print_dist = QtWidgets.QPushButton(self.centralwidget)
        self.Print_dist.setGeometry(QtCore.QRect(230, 830, 80, 30))
        self.Print_dist.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_dist.setObjectName("Print_dist")
        self.Print_prop = QtWidgets.QPushButton(self.centralwidget)
        self.Print_prop.setGeometry(QtCore.QRect(230, 880, 80, 30))
        self.Print_prop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_prop.setObjectName("Print_prop")
        self.Print_product = QtWidgets.QPushButton(self.centralwidget)
        self.Print_product.setGeometry(QtCore.QRect(230, 630, 80, 30))
        self.Print_product.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_product.setObjectName("Print_product")
        self.Q_3_8_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_8.setGeometry(QtCore.QRect(640, 600, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Q_3_8_8.setFont(font)
        self.Q_3_8_8.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_8.setObjectName("Q_3_8_8")
        self.Q_3_8_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_9.setGeometry(QtCore.QRect(640, 640, 401, 31))
        self.Q_3_8_9.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_9.setObjectName("Q_3_8_9")
        self.Q_3_8_10 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_10.setGeometry(QtCore.QRect(640, 680, 401, 31))
        self.Q_3_8_10.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_10.setObjectName("Q_3_8_10")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 490, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.Q_3_8_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_7.setGeometry(QtCore.QRect(880, 530, 41, 31))
        self.Q_3_8_7.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_7.setObjectName("Q_3_8_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(650, 330, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 32px;\n"
"font: \"Arial Black\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Q_3_8_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_1.setGeometry(QtCore.QRect(660, 440, 41, 31))
        self.Q_3_8_1.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_1.setObjectName("Q_3_8_1")
        self.Q_3_8_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_4.setGeometry(QtCore.QRect(990, 440, 41, 31))
        self.Q_3_8_4.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_4.setObjectName("Q_3_8_4")
        self.Q_3_8_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_6.setGeometry(QtCore.QRect(770, 530, 41, 31))
        self.Q_3_8_6.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_6.setObjectName("Q_3_8_6")
        self.Q_3_8_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_5.setGeometry(QtCore.QRect(660, 530, 41, 31))
        self.Q_3_8_5.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_5.setObjectName("Q_3_8_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(650, 389, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Q_3_8_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_3.setGeometry(QtCore.QRect(880, 440, 41, 31))
        self.Q_3_8_3.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_3.setObjectName("Q_3_8_3")
        self.Q_3_8_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_2.setGeometry(QtCore.QRect(770, 440, 41, 31))
        self.Q_3_8_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_2.setObjectName("Q_3_8_2")
        self.Q_3_9_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_1.setGeometry(QtCore.QRect(640, 720, 401, 31))
        self.Q_3_9_1.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_1.setObjectName("Q_3_9_1")
        self.Q_3_9_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_3.setGeometry(QtCore.QRect(640, 800, 401, 31))
        self.Q_3_9_3.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_3.setObjectName("Q_3_9_3")
        self.Q_3_9_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_2.setGeometry(QtCore.QRect(640, 760, 401, 31))
        self.Q_3_9_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_2.setObjectName("Q_3_9_2")
        self.Q_3_9_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_4.setGeometry(QtCore.QRect(640, 840, 401, 31))
        self.Q_3_9_4.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_4.setObjectName("Q_3_9_4")
        self.Q_3_9_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_6.setGeometry(QtCore.QRect(640, 920, 401, 31))
        self.Q_3_9_6.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_6.setObjectName("Q_3_9_6")
        self.Q_3_9_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_5.setGeometry(QtCore.QRect(640, 880, 401, 31))
        self.Q_3_9_5.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_5.setObjectName("Q_3_9_5")
        self.add_customer = QtWidgets.QPushButton(self.centralwidget)
        self.add_customer.setGeometry(QtCore.QRect(370, 580, 80, 30))
        self.add_customer.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_customer.setObjectName("add_customer")
        self.add_product = QtWidgets.QPushButton(self.centralwidget)
        self.add_product.setGeometry(QtCore.QRect(370, 630, 80, 30))
        self.add_product.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_product.setObjectName("add_product")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 330, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 530, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 580, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 630, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 780, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 830, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 880, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.add_print = QtWidgets.QPushButton(self.centralwidget)
        self.add_print.setGeometry(QtCore.QRect(370, 530, 80, 30))
        self.add_print.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_print.setObjectName("add_print")
        self.add_order = QtWidgets.QPushButton(self.centralwidget)
        self.add_order.setGeometry(QtCore.QRect(370, 780, 80, 30))
        self.add_order.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_order.setObjectName("add_order")
        self.add_dist = QtWidgets.QPushButton(self.centralwidget)
        self.add_dist.setGeometry(QtCore.QRect(370, 830, 80, 30))
        self.add_dist.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_dist.setObjectName("add_dist")
        self.add_prop = QtWidgets.QPushButton(self.centralwidget)
        self.add_prop.setGeometry(QtCore.QRect(370, 880, 80, 30))
        self.add_prop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_prop.setObjectName("add_prop")
        self.print = QtWidgets.QPushButton(self.centralwidget)
        self.print.setGeometry(QtCore.QRect(30, 390, 41, 31))
        self.print.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.print.setObjectName("print")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(30, 450, 41, 31))
        self.add.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add.setObjectName("add")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(90, 390, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(90, 450, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(240, 390, 161, 31))
        self.DeleteButton.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.DeleteButton.setObjectName("DeleteButton")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 930, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.add_prod_type = QtWidgets.QPushButton(self.centralwidget)
        self.add_prod_type.setGeometry(QtCore.QRect(370, 930, 80, 30))
        self.add_prod_type.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_prod_type.setObjectName("add_prod_type")
        self.Print_prod_type = QtWidgets.QPushButton(self.centralwidget)
        self.Print_prod_type.setGeometry(QtCore.QRect(230, 930, 80, 30))
        self.Print_prod_type.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_prod_type.setObjectName("Print_prod_type")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 680, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.add_density = QtWidgets.QPushButton(self.centralwidget)
        self.add_density.setGeometry(QtCore.QRect(370, 680, 80, 30))
        self.add_density.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_density.setObjectName("add_density")
        self.Print_density = QtWidgets.QPushButton(self.centralwidget)
        self.Print_density.setGeometry(QtCore.QRect(230, 680, 80, 30))
        self.Print_density.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_density.setObjectName("Print_density")
        self.generate_print = QtWidgets.QPushButton(self.centralwidget)
        self.generate_print.setGeometry(QtCore.QRect(510, 530, 80, 30))
        self.generate_print.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_print.setObjectName("generate_print")
        self.generate_customer = QtWidgets.QPushButton(self.centralwidget)
        self.generate_customer.setGeometry(QtCore.QRect(510, 580, 80, 30))
        self.generate_customer.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_customer.setObjectName("generate_customer")
        self.generate_product = QtWidgets.QPushButton(self.centralwidget)
        self.generate_product.setGeometry(QtCore.QRect(510, 630, 80, 30))
        self.generate_product.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_product.setObjectName("generate_product")
        self.add_2 = QtWidgets.QPushButton(self.centralwidget)
        self.add_2.setGeometry(QtCore.QRect(240, 450, 41, 31))
        self.add_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_2.setObjectName("add_2")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(290, 450, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.generate_density = QtWidgets.QPushButton(self.centralwidget)
        self.generate_density.setGeometry(QtCore.QRect(510, 680, 80, 30))
        self.generate_density.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_density.setObjectName("generate_density")
        self.generate_order = QtWidgets.QPushButton(self.centralwidget)
        self.generate_order.setGeometry(QtCore.QRect(510, 780, 80, 30))
        self.generate_order.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_order.setObjectName("generate_order")
        self.generate_dist = QtWidgets.QPushButton(self.centralwidget)
        self.generate_dist.setGeometry(QtCore.QRect(510, 830, 80, 30))
        self.generate_dist.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_dist.setObjectName("generate_dist")
        self.generate_prop = QtWidgets.QPushButton(self.centralwidget)
        self.generate_prop.setGeometry(QtCore.QRect(510, 880, 80, 30))
        self.generate_prop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_prop.setObjectName("generate_prop")
        self.generate_prod_type = QtWidgets.QPushButton(self.centralwidget)
        self.generate_prod_type.setGeometry(QtCore.QRect(510, 930, 80, 30))
        self.generate_prod_type.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_prod_type.setObjectName("generate_prod_type")
        self.excel = QtWidgets.QPushButton(self.centralwidget)
        self.excel.setGeometry(QtCore.QRect(430, 390, 161, 31))
        self.excel.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.excel.setObjectName("excel")
        self.gen_label = QtWidgets.QLabel(self.centralwidget)
        self.gen_label.setGeometry(QtCore.QRect(10, 480, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gen_label.setFont(font)
        self.gen_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.gen_label.setText("")
        self.gen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gen_label.setObjectName("gen_label")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 730, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.Print_density_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Print_density_2.setGeometry(QtCore.QRect(230, 730, 80, 30))
        self.Print_density_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_density_2.setObjectName("Print_density_2")
        self.add_paper = QtWidgets.QPushButton(self.centralwidget)
        self.add_paper.setGeometry(QtCore.QRect(370, 730, 80, 30))
        self.add_paper.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_paper.setObjectName("add_paper")
        self.generate_paper = QtWidgets.QPushButton(self.centralwidget)
        self.generate_paper.setGeometry(QtCore.QRect(510, 730, 80, 30))
        self.generate_paper.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.generate_paper.setObjectName("generate_paper")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Бойко С.Р., ПИ-20а, курсовая работа БД, вариант №13"))
        self.Print_print.setText(_translate("MainWindow", "П"))
        self.Print_customer.setText(_translate("MainWindow", "П"))
        self.Print_order.setText(_translate("MainWindow", "П"))
        self.Print_dist.setText(_translate("MainWindow", "П"))
        self.Print_prop.setText(_translate("MainWindow", "П"))
        self.Print_product.setText(_translate("MainWindow", "П"))
        self.Q_3_8_8.setText(_translate("MainWindow", "левое внешнее соединение"))
        self.Q_3_8_9.setText(_translate("MainWindow", "правое внешнее соединение"))
        self.Q_3_8_10.setText(_translate("MainWindow", "запрос на запросе по принципу левого соединения "))
        self.label_5.setText(_translate("MainWindow", "симметричное внутреннее соединение без условия "))
        self.Q_3_8_7.setText(_translate("MainWindow", "3"))
        self.label_6.setText(_translate("MainWindow", "Выполнить запрос"))
        self.Q_3_8_1.setText(_translate("MainWindow", "1"))
        self.Q_3_8_4.setText(_translate("MainWindow", "4"))
        self.Q_3_8_6.setText(_translate("MainWindow", "2"))
        self.Q_3_8_5.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "симметричное внутреннее соединение с условием"))
        self.Q_3_8_3.setText(_translate("MainWindow", "3"))
        self.Q_3_8_2.setText(_translate("MainWindow", "2"))
        self.Q_3_9_1.setText(_translate("MainWindow", "итоговый запрос без условия "))
        self.Q_3_9_3.setText(_translate("MainWindow", "итоговый запрос с условием на группы"))
        self.Q_3_9_2.setText(_translate("MainWindow", "итоговый запрос с условием на данные"))
        self.Q_3_9_4.setText(_translate("MainWindow", "итоговый запрос с условием на данные и на группы "))
        self.Q_3_9_6.setText(_translate("MainWindow", "запрос с подзапросом "))
        self.Q_3_9_5.setText(_translate("MainWindow", "запрос на запросе по принципу итогового запроса "))
        self.add_customer.setText(_translate("MainWindow", "Д"))
        self.add_product.setText(_translate("MainWindow", "Д"))
        self.label_2.setText(_translate("MainWindow", "Вы работаете в режиме администратора!"))
        self.label_3.setText(_translate("MainWindow", "Типографии"))
        self.label_4.setText(_translate("MainWindow", "Заказчики"))
        self.label_8.setText(_translate("MainWindow", "Изделия"))
        self.label_9.setText(_translate("MainWindow", "Заказы"))
        self.label_10.setText(_translate("MainWindow", "Районы"))
        self.label_12.setText(_translate("MainWindow", "Тип собственности"))
        self.add_print.setText(_translate("MainWindow", "Д"))
        self.add_order.setText(_translate("MainWindow", "Д"))
        self.add_dist.setText(_translate("MainWindow", "Д"))
        self.add_prop.setText(_translate("MainWindow", "Д"))
        self.print.setText(_translate("MainWindow", "П"))
        self.add.setText(_translate("MainWindow", "Д"))
        self.label_14.setText(_translate("MainWindow", "- просмотреть"))
        self.label_15.setText(_translate("MainWindow", "- добавить"))
        self.DeleteButton.setText(_translate("MainWindow", "Удалить запись"))
        self.label_16.setText(_translate("MainWindow", "Вид изделия"))
        self.add_prod_type.setText(_translate("MainWindow", "Д"))
        self.Print_prod_type.setText(_translate("MainWindow", "П"))
        self.label_11.setText(_translate("MainWindow", "Плотность бумаги"))
        self.add_density.setText(_translate("MainWindow", "Д"))
        self.Print_density.setText(_translate("MainWindow", "П"))
        self.generate_print.setText(_translate("MainWindow", "Г"))
        self.generate_customer.setText(_translate("MainWindow", "Г"))
        self.generate_product.setText(_translate("MainWindow", "Г"))
        self.add_2.setText(_translate("MainWindow", "Г"))
        self.label_17.setText(_translate("MainWindow", "- сгенерировать 10 тыс. записей"))
        self.generate_density.setText(_translate("MainWindow", "Г"))
        self.generate_order.setText(_translate("MainWindow", "Г"))
        self.generate_dist.setText(_translate("MainWindow", "Г"))
        self.generate_prop.setText(_translate("MainWindow", "Г"))
        self.generate_prod_type.setText(_translate("MainWindow", "Г"))
        self.excel.setText(_translate("MainWindow", "Выгрузка в Excel"))
        self.label_13.setText(_translate("MainWindow", "Тип бумаги"))
        self.Print_density_2.setText(_translate("MainWindow", "П"))
        self.add_paper.setText(_translate("MainWindow", "Д"))
        self.generate_paper.setText(_translate("MainWindow", "Г"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
